version: "3.9"

services:
  lnl-examples:
    image: fauxneticien/ptl2:lnl-examples
    volumes:
      - ${PWD}:/root
    working_dir: /root
    entrypoint:
      - /bin/bash
    stdin_open: true
    tty: true
    # Default shm_size of 64mb is too small for distributed training
    shm_size: '16gb'
    # Service must be network host for distributed training
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
